# Generated by Django 4.2.16 on 2024-09-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="banner",
            table="cc_banner",
        ),
    ]
